[server]
# Set to true to enable CORS for all domains
enableCORS = true

# Set to true to enable XSS protection
enableXsrfProtection = true

# Set to true to enable the file watcher. This is useful for development
fileWatcherType = "none"

# The port where the server will listen for browser connections
port = 8501

# The base path for the URL where Streamlit should be served from
baseUrlPath = "/"

# The folder where your app's static files should be served from
staticFolder = "static"

# The folder where your app's data should be stored
dataFolder = "data"

# The folder where your app's cache should be stored
cacheFolder = "cache"

[browser]
# The browser that Streamlit should use to open the app
serverAddress = "localhost"

# The port that Streamlit should use to open the app
serverPort = 8501
